### ISSUE TITLE
How can you add sass to the project?

### ISSUE THREAD

**Issue by EddyTheDove** [myst729/vue-webpack-2#1]
I would like to add sass support to my project. How do you add it so that webpack can compile it during build process. I never used webpack before ever.

**Comment by myst729** [comment]
You need to install **sass-loader**, and let the loader to deal with __*.sass__ or __*.scss__ files in the webpack config file. Just like how I use **stylus-load** with __*styl__ files:

```js
      {
        test: /\.(sass|scss)$/,
        loader: ExtractTextPlugin.extract('css-loader!sass-loader')        
      },
```

However, this repo is quite outdated. Webpack 2 has entered stable phase. I recommend you to use https://github.com/vuejs-templates/webpack with **vue-cli**.
